[workspace]
members = ["crates/yachtpit", "crates/yachtpit/mobile", "crates/systems", "crates/components"]
resolver = "2"

default-members = [
    "crates/yachtpit"
]

[workspace.dependencies]
bevy = { version = "0.16", default-features = false }
wasm-bindgen = "=0.2.100"
