[workspace]
members = ["crates/yachtpit", "crates/yachtpit/mobile", "crates/models"]
resolver = "2"

default-members = [
    "crates/yachtpit"
]

[workspace.dependencies]
bevy = { version = "0.16", default-features = false }
